# Generated by Django 2.1.1 on 2018-09-14 06:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('rules', models.TextField(blank=True)),
                ('moderators', models.ManyToManyField(related_name='moderators', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
