# Generated by Django 2.1.1 on 2018-09-11 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='rules',
            field=models.TextField(blank=True),
        ),
    ]
