# Generated by Django 2.1.1 on 2018-10-10 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0002_auto_20181001_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield'),
        ),
    ]
