# Generated by Django 2.1.1 on 2018-09-16 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('channel', '0002_channel_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='blacklist',
            field=models.ManyToManyField(related_name='blacklist', to='profile.Profile'),
        ),
    ]
