# Generated by Django 2.1.1 on 2018-10-10 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel', '0003_channel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='slug',
            field=models.SlugField(allow_unicode=True),
        ),
    ]
