# Generated by Django 2.1.1 on 2018-09-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='downvoted',
        ),
        migrations.AddField(
            model_name='article',
            name='downvoted',
            field=models.ManyToManyField(blank=True, related_name='downvotes', to='profile.Profile'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='upvoted',
        ),
        migrations.AddField(
            model_name='article',
            name='upvoted',
            field=models.ManyToManyField(blank=True, related_name='upvotes', to='profile.Profile'),
        ),
    ]
