# Generated by Django 2.1.1 on 2018-09-17 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='downvoted',
        ),
        migrations.AddField(
            model_name='article',
            name='downvoted',
            field=models.ManyToManyField(blank=True, related_name='downvoted', to='profile.Profile'),
        ),
        migrations.RemoveField(
            model_name='article',
            name='upvoted',
        ),
        migrations.AddField(
            model_name='article',
            name='upvoted',
            field=models.ManyToManyField(blank=True, related_name='upvoted', to='profile.Profile'),
        ),
        migrations.AlterField(
            model_name='article',
            name='writer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='post.Comment'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.Article'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='writer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile'),
        ),
    ]
